apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: c93vf23pt-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: c93vf23pt-go 
  name: c93vf23pt-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: c93vf23pt-go 
